/**
 * List of all possible events that can be emitted by the Streamerbot WebSocket server
 *
 * Compiled from the raw output of the `GetEvents` request
 */
export const StreamerbotEvents = {
  General: ['Custom'],
  Twitch: [
    'Follow',
    'Cheer',
    'Sub',
    'ReSub',
    'GiftSub',
    'GiftBomb',
    'Raid',
    'HypeTrainStart',
    'HypeTrainUpdate',
    'HypeTrainLevelUp',
    'HypeTrainEnd',
    'RewardRedemption',
    'RewardCreated',
    'RewardUpdated',
    'RewardDeleted',
    'CommunityGoalContribution',
    'CommunityGoalEnded',
    'StreamUpdate',
    'Whisper',
    'FirstWord',
    'SubCounterRollover',
    'BroadcastUpdate',
    'StreamUpdateGameOnConnect',
    'PresentViewers',
    'PollCreated',
    'PollUpdated',
    'PollCompleted',
    'PredictionCreated',
    'PredictionUpdated',
    'PredictionCompleted',
    'PredictionCanceled',
    'PredictionLocked',
    'ChatMessage',
    'ChatMessageDeleted',
    'UserTimedOut',
    'UserBanned',
    'Announcement',
    'AdRun',
    'BotWhisper',
    'CharityDonation',
    'CharityCompleted',
    'CoinCheer',
    'ShoutoutCreated',
    'UserUntimedOut',
    'CharityStarted',
    'CharityProgress',
    'GoalBegin',
    'GoalProgress',
    'GoalEnd',
    'ShieldModeBegin',
    'ShieldModeEnd',
    'AdMidRoll',
    'StreamOnline',
    'StreamOffline',
    'ShoutoutReceived',
    'ChatCleared',
    'RaidStart',
    'RaidSend',
    'RaidCancelled',
    'PollTerminated',
    'PyramidSuccess',
    'PyramidBroken',
    'ViewerCountUpdate',
    'GuestStarSessionBegin',
    'GuestStarSessionEnd',
    'GuestStarGuestUpdate',
    'GuestStarSlotUpdate',
    'GuestStarSettingsUpdate',
    'HypeChat',
    'RewardRedemptionUpdated',
    'HypeChatLevel',
    'BroadcasterAuthenticated',
    'BroadcasterChatConnected',
    'BroadcasterChatDisconnected',
    'BroadcasterPubSubConnected',
    'BroadcasterPubSubDisconnected',
    'BroadcasterEventSubConnected',
    'BroadcasterEventSubDisconnected',
    'SevenTVEmoteAdded',
    'SevenTVEmoteRemoved',
    'BetterTTVEmoteAdded',
    'BetterTTVEmoteRemoved',
    'BotChatConnected',
    'BotChatDisconnected',
    'UpcomingAd',
    'ModeratorAdded',
    'ModeratorRemoved',
    'VipAdded',
    'VipRemoved',
    'UserUnbanned',
    'UnbanRequestApproved',
    'UnbanRequestDenied',
    'AutomaticRewardRedemption',
    'UnbanRequestCreated',
    'ChatEmoteModeOn',
    'ChatEmoteModeOff',
    'ChatFollowerModeOn',
    'ChatFollowerModeOff',
    'ChatFollowerModeChanged',
    'ChatSlowModeOn',
    'ChatSlowModeOff',
    'ChatSlowModeChanged',
    'ChatSubscriberModeOn',
    'ChatSubscriberModeOff',
    'ChatUniqueModeOn',
    'ChatUniqueModeOff',
    'AutoModMessageHeld',
    'AutoModMessageUpdate',
    'BlockedTermsAdded',
    'BlockedTermsDeleted',
    'WarnedUser',
    'SuspiciousUserUpdate',
    'PermittedTermsAdded',
    'PermittedTermsDeleted',
    'WarningAcknowledged',
    'WatchStreak',
    'PollArchived',
    'SharedChatSessionBegin',
    'SharedChatSessionUpdate',
    'SharedChatSessionEnd',
    'PrimePaidUpgrade',
    'PayItForward',
    'GiftPaidUpgrade',
    'BitsBadgeTier',
    'SharedAnnouncement',
    'SharedRaid',
    'SharedPrimePaidUpgrade',
    'SharedGiftPaidUpgrade',
    'SharedPayItForward',
    'SharedSub',
    'SharedResub',
    'SharedSubGift',
    'SharedCommunitySubGift',
  ],
  Streamlabs: ['Donation', 'Merchandise', 'Connected', 'Disconnected', 'CharityDonation'],
  SpeechToText: ['Dictation', 'Command'],
  Command: ['Triggered', 'Cooldown'],
  FileWatcher: ['Changed', 'Created', 'Deleted', 'Renamed'],
  FileTail: ['Changed'],
  Quote: ['Added', 'Show'],
  Misc: [
    'TimedAction',
    'Test',
    'ProcessStarted',
    'ProcessStopped',
    'ChatWindowAction',
    'StreamerbotStarted',
    'StreamerbotExiting',
    'ToastActivation',
    'GlobalVariableUpdated',
    'UserGlobalVariableUpdated',
    'ApplicationImport',
  ],
  Raw: ['Action', 'SubAction', 'ActionCompleted'],
  WebsocketClient: ['Open', 'Close', 'Message'],
  StreamElements: ['Tip', 'Merch', 'Connected', 'Disconnected', 'Authenticated'],
  WebsocketCustomServer: ['Open', 'Close', 'Message'],
  DonorDrive: ['Donation', 'ProfileUpdated', 'Incentive'],
  YouTube: [
    'BroadcastStarted',
    'BroadcastEnded',
    'Message',
    'MessageDeleted',
    'UserBanned',
    'SuperChat',
    'SuperSticker',
    'NewSponsor',
    'MemberMileStone',
    'NewSponsorOnlyStarted',
    'NewSponsorOnlyEnded',
    'StatisticsUpdated',
    'BroadcastUpdated',
    'MembershipGift',
    'GiftMembershipReceived',
    'FirstWords',
    'PresentViewers',
    'NewSubscriber',
    'BroadcastMonitoringStarted',
    'BroadcastMonitoringEnded',
    'BroadcastAdded',
    'BroadcastRemoved',
    'SevenTVEmoteAdded',
    'SevenTVEmoteRemoved',
    'BetterTTVEmoteAdded',
    'BetterTTVEmoteRemoved',
  ],
  Pulsoid: ['HeartRatePulse'],
  HypeRate: ['HeartRatePulse', 'TwitchClipCreated', 'Connected', 'Disconnected'],
  Kofi: ['Donation', 'Subscription', 'Resubscription', 'ShopOrder', 'Commission'],
  Patreon: ['FollowCreated', 'FollowDeleted', 'PledgeCreated', 'PledgeUpdated', 'PledgeDeleted'],
  Application: ['ActionAdded', 'ActionUpdated', 'ActionDeleted'],
  TipeeeStream: ['Donation'],
  TreatStream: ['Treat', 'Authenticated', 'Connected', 'Disconnected'],
  Shopify: ['OrderCreated', 'OrderPaid'],
  Obs: [
    'Connected',
    'Disconnected',
    'Event',
    'SceneChanged',
    'StreamingStarted',
    'StreamingStopped',
    'RecordingStarted',
    'RecordingStopped',
    'VendorEvent',
  ],
  Midi: ['Message'],
  HotKey: ['Press'],
  StreamDeck: ['Action', 'Connected', 'Disconnected', 'Info'],
  Custom: ['Event', 'CodeEvent'],
  VTubeStudio: [
    'ModelLoaded',
    'ModelUnloaded',
    'BackgroundChanged',
    'ModelConfigChanged',
    'HotkeyTriggered',
    'ModelAnimation',
    'Connected',
    'Disconnected',
    'TrackingStatusChanged',
    'ItemEvent',
    'ModelClicked',
  ],
  CrowdControl: [
    'GameSessionStart',
    'GameSessionEnd',
    'EffectRequest',
    'EffectSuccess',
    'EffectFailure',
    'TimedEffectStarted',
    'TimedEffectEnded',
    'TimedEffectUpdated',
    'CoinExchange',
  ],
  Elgato: [
    'WaveLinkOutputSwitched',
    'WaveLinkOutputVolumeChanged',
    'WaveLinkOutputMuteChanged',
    'WaveLinkSelectedOutputChanged',
    'WaveLinkInputVolumeChanged',
    'WaveLinkInputMuteChanged',
    'WaveLinkInputNameChanged',
    'WaveLinkMicrophoneGainChanged',
    'WaveLinkMicrophoneOutputVolumeChanged',
    'WaveLinkMicrophoneBalanceChanged',
    'WaveLinkMicrophoneMuteChanged',
    'WaveLinkMicrophoneSettingChanged',
    'WaveLinkFilterAdded',
    'WaveLinkFilterChanged',
    'WaveLinkFilterDeleted',
    'WaveLinkFilterBypassStateChanged',
    'WaveLinkConnected',
    'WaveLinkDisconnected',
    'WaveLinkInputLevelMeterChanged',
    'WaveLinkOutputLevelMeterChanged',
    'CameraHubConnected',
    'CameraHubDisconnected',
    'CameraHubWebcamConnected',
    'CameraHubWebcamrDisconnected',
    'CameraHubWebcamActivated',
    'CameraHubWebcamDeactivated',
    'CameraHubSelectedWebcamChanged',
    'CameraHubWebcamMirrored',
    'CameraHubWebcamFlipped',
    'CameraHubWebcamDeviceOrientationChanged',
    'CameraHubWebcamExposureAutoLockEnabled',
    'CameraHubWebcamExposureAutoLockDisabled',
    'CameraHubWebcamSnapshotTaken',
    'CameraHubWebcamZoomChanged',
    'CameraHubWebcamContrastChanged',
    'CameraHubWebcamWhiteBalanceChanged',
    'CameraHubWebcamAutoExposureEnabled',
    'CameraHubWebcamAutoExposureDisabled',
    'CameraHubWebcamAutoWhiteBalanceEnabled',
    'CameraHubWebcamAutoWhiteBalanceDisabled',
    'CameraHubWebcamNoiseReductionEnabled',
    'CameraHubWebcamNoiseReductionDisabled',
    'CameraHubWebcamISOChanged',
    'CameraHubWebcamShutterSpeedChanged',
    'CameraHubWebcamSharpnessChanged',
    'CameraHubWebcamAntiFlickerChanged',
    'CameraHubWebcamLensChanged',
    'CameraHubWebcamARLensChanged',
    'CameraHubWebcamBitrateChanged',
    'CameraHubWebcamFlashEnabled',
    'CameraHubWebcamFlashDisabled',
    'CameraHubWebcamPanChanged',
    'CameraHubTiltChanged',
    'CameraHubWebcamOverscanChanged',
    'CameraHubWebcamAutoFocusEnabled',
    'CameraHubWebcamAutoFocusDisabled',
    'CameraHubWebcamFocusChanged',
    'CameraHubWebcamWhiteBalanceTintChanged',
    'CameraHubWebcamBrightnessChanged',
    'CameraHubWebcamSaturationChanged',
    'CameraHubWebcamLiveISOChanged',
    'CameraHubWebcamLiveShutterSpeedChanged',
    'CameraHubWebcamLiveWhiteBalanceChanged',
    'CameraHubWebcamLiveWhiteBalanceTintChanged',
    'CameraHubPrompterConnected',
    'CameraHubPrompterDisconnected',
    'CameraHubPrompterModeChanged',
    'CameraHubPrompterBrightnessChanged',
    'CameraHubPrompterFontChanged',
    'CameraHubPrompterFontSizeChanged',
    'CameraHubPrompterAutoScrollEnabled',
    'CameraHubPrompterAutoScrollDisabled',
    'CameraHubPrompterAutoScrollChapterEnabled',
    'CameraHubPrompterAutoScrollChapterDisabled',
    'CameraHubPrompterScrollSpeedChanged',
    'CameraHubPrompterOpacityChanged',
    'CameraHubPrompterHorizontalMarginChanged',
    'CameraHubPrompterVerticalMarginChanged',
    'CameraHubPrompterLineSpacingChanged',
    'CameraHubPrompterFontColorChanged',
    'CameraHubPrompterBackgroundColorChanged',
    'CameraHubPrompterSelectedChapterChanged',
    'CameraHubPrompterChannelsChanged',
    'CameraHubPrompterSelectedChannelChanged',
    'CameraHubPrompterContrastChanged',
    'CameraHubPrompterCrosshairEnabled',
    'CameraHubPrompterCrosshairDisabled',
    'CameraHubPrompterCrosshairImageChanged',
    'CameraHubPrompterCrosshairColorChanged',
    'CameraHubPrompterSelectedScriptChanged',
  ],
  StreamlabsDesktop: [
    'Connected',
    'Disconnected',
    'SceneChanged',
    'StreamingStarted',
    'StreamingStopped',
    'RecordingStarted',
    'RecordingStopped',
  ],
  SpeakerBot: ['Connected', 'Disconnected'],
  Fourthwall: [
    'ProductCreated',
    'ProductUpdated',
    'GiftPurchase',
    'OrderPlaced',
    'OrderUpdated',
    'Donation',
    'SubscriptionPurchased',
    'SubscriptionExpired',
    'SubscriptionChanged',
    'ThankYouSent',
    'NewsletterSubscribed',
    'GiftDrawStarted',
    'GiftDrawEnded',
  ],
  Trovo: [
    'BroadcasterAuthenticated',
    'BroadcasterChatConnected',
    'BroadcasterChatDisconnected',
    'FirstWords',
    'PresentViewers',
    'ChatMessage',
    'Follow',
    'SpellCast',
    'CustomSpellCast',
    'Raid',
    'Subscription',
    'Resubscription',
    'GiftSubscription',
    'MassGiftSubscription',
    'StreamOnline',
    'StreamOffline',
  ],
  ThrowingSystem: [
    'Connected',
    'WebsocketConnected',
    'WebsocketDisconnected',
    'EventsConnected',
    'EventsDisconnected',
    'ItemHit',
    'TriggerActivated',
    'TriggerEnded',
  ],
  Pallygg: ['Connected', 'Disconnected', 'CampaignTip'],
  StreamerBotRemote: [
    'InstanceConnected',
    'InstanceDisconnected',
    'InstanceTrigger',
    'InstanceSignal',
  ],
  VoiceMod: ['Connected', 'Disconnected', 'VoiceLoaded', 'SoundboardChanged'],
  Group: ['Added', 'Removed', 'Cleared', 'UsersAdded', 'UsersRemoved'],
  MeldStudio: [
    'Connected',
    'Disconnected',
    'StreamingStarted',
    'StreamingStopped',
    'RecordingStarted',
    'RecordingStopped',
    'SceneChanged',
    'LayerVisbilityChanged',
    'LEffectEnabledStateChanged',
    'TrackMonitoringStateChanged',
    'TrackMustedStateChanged',
    'Event',
  ],
} as const;
