/**
 * List of all possible events that can be emitted by the Streamerbot WebSocket server
 *
 * Compiled from the raw output of the `GetEvents` request
 */
export const StreamerbotEvents = {
  General: ['Custom'],
  Twitch: [
    'AdMidRoll',
    'AdRun',
    'Announcement',
    'BetterTTVEmoteAdded',
    'BetterTTVEmoteRemoved',
    'BotChatConnected',
    'BotChatDisconnected',
    'BotWhisper',
    'BroadcasterAuthenticated',
    'BroadcasterChatConnected',
    'BroadcasterChatDisconnected',
    'BroadcasterEventSubConnected',
    'BroadcasterEventSubDisconnected',
    'BroadcasterPubSubConnected',
    'BroadcasterPubSubDisconnected',
    'BroadcastUpdate',
    'CharityCompleted',
    'CharityDonation',
    'CharityProgress',
    'CharityStarted',
    'ChatCleared',
    'ChatEmoteModeOff',
    'ChatEmoteModeOn',
    'ChatFollowerModeChanged',
    'ChatFollowerModeOff',
    'ChatFollowerModeOn',
    'ChatMessage',
    'ChatMessageDeleted',
    'ChatSlowModeChanged',
    'ChatSlowModeOff',
    'ChatSlowModeOn',
    'ChatSubscriberModeOff',
    'ChatSubscriberModeOn',
    'ChatUniqueModeOff',
    'ChatUniqueModeOn',
    'Cheer',
    'CoinCheer',
    'CommunityGoalContribution',
    'CommunityGoalEnded',
    'FirstWord',
    'Follow',
    'GiftBomb',
    'GiftSub',
    'GoalBegin',
    'GoalEnd',
    'GoalProgress',
    'GuestStarGuestUpdate',
    'GuestStarSessionBegin',
    'GuestStarSessionEnd',
    'GuestStarSettingsUpdate',
    'GuestStarSlotUpdate',
    'HypeChat',
    'HypeChatLevel',
    'HypeTrainEnd',
    'HypeTrainLevelUp',
    'HypeTrainStart',
    'HypeTrainUpdate',
    'ModeratorAdded',
    'ModeratorRemoved',
    'PollCompleted',
    'PollCreated',
    'PollTerminated',
    'PollUpdated',
    'PredictionCanceled',
    'PredictionCompleted',
    'PredictionCreated',
    'PredictionLocked',
    'PredictionUpdated',
    'PresentViewers',
    'PyramidBroken',
    'PyramidSuccess',
    'Raid',
    'RaidCancelled',
    'RaidSend',
    'RaidStart',
    'ReSub',
    'RewardCreated',
    'RewardDeleted',
    'RewardRedemption',
    'RewardRedemptionUpdated',
    'RewardUpdated',
    'SevenTVEmoteAdded',
    'SevenTVEmoteRemoved',
    'ShieldModeBegin',
    'ShieldModeEnd',
    'ShoutoutCreated',
    'ShoutoutReceived',
    'StreamOffline',
    'StreamOnline',
    'StreamUpdate',
    'StreamUpdateGameOnConnect',
    'Sub',
    'SubCounterRollover',
    'UpcomingAd',
    'UserBanned',
    'UserTimedOut',
    'UserUntimedOut',
    'ViewerCountUpdate',
    'VipAdded',
    'Whisper',
  ],
  Streamlabs: ['Donation', 'Merchandise', 'Connected', 'Disconnected'],
  SpeechToText: ['Dictation', 'Command'],
  Command: ['Triggered', 'Cooldown'],
  FileWatcher: ['Changed', 'Created', 'Deleted', 'Renamed'],
  FileTail: ['Changed'],
  Quote: ['Added', 'Show'],
  Misc: [
    'ApplicationImport',
    'ChatWindowAction',
    'GlobalVariableUpdated',
    'ProcessStarted',
    'ProcessStopped',
    'StreamerbotExiting',
    'StreamerbotStarted',
    'Test',
    'TimedAction',
    'ToastActivation',
  ],
  Raw: ['Action', 'SubAction', 'ActionCompleted'],
  WebsocketClient: ['Open', 'Close', 'Message'],
  StreamElements: ['Tip', 'Merch', 'Connected', 'Disconnected'],
  WebsocketCustomServer: ['Open', 'Close', 'Message'],
  DonorDrive: ['Donation', 'ProfileUpdated', 'Incentive'],
  YouTube: [
    'BroadcastEnded',
    'BroadcastStarted',
    'BroadcastUpdated',
    'FirstWords',
    'GiftMembershipReceived',
    'MemberMileStone',
    'MembershipGift',
    'Message',
    'MessageDeleted',
    'NewSponsor',
    'NewSponsorOnlyEnded',
    'NewSponsorOnlyStarted',
    'NewSubscriber',
    'PresentViewers',
    'StatisticsUpdated',
    'SuperChat',
    'SuperSticker',
    'UserBanned',
  ],
  Pulsoid: ['HeartRatePulse'],
  HypeRate: ['HeartRatePulse'],
  Kofi: ['Donation', 'Subscription', 'Resubscription', 'ShopOrder', 'Commission'],
  Patreon: ['FollowCreated', 'FollowDeleted', 'PledgeCreated', 'PledgeUpdated', 'PledgeDeleted'],
  Application: ['ActionAdded', 'ActionUpdated', 'ActionDeleted'],
  TipeeeStream: ['Donation'],
  TreatStream: ['Treat'],
  Shopify: ['OrderCreated', 'OrderPaid'],
  Obs: [
    'Connected',
    'Disconnected',
    'Event',
    'RecordingStarted',
    'RecordingStopped',
    'SceneChanged',
    'StreamingStarted',
    'StreamingStopped',
  ],
  Midi: ['Message'],
  HotKey: ['Press'],
  StreamDeck: ['Action', 'Connected', 'Disconnected', 'Info'],
  Custom: ['Event', 'CodeEvent'],
  VTubeStudio: [
    'BackgroundChanged',
    'Connected',
    'Disconnected',
    'HotkeyTriggered',
    'ItemEvent',
    'ModelAnimation',
    'ModelClicked',
    'ModelConfigChanged',
    'ModelLoaded',
    'ModelUnloaded',
    'TrackingStatusChanged',
  ],
  CrowdControl: [
    'EffectFailure',
    'EffectRequest',
    'EffectSuccess',
    'GameSessionEnd',
    'GameSessionStart',
    'TimedEffectEnded',
    'TimedEffectStarted',
    'TimedEffectUpdated',
  ],
  Elgato: [
    'CameraHubConnected',
    'CameraHubDisconnected',
    'CameraHubPrompterAutoScrollChapterDisabled',
    'CameraHubPrompterAutoScrollChapterEnabled',
    'CameraHubPrompterAutoScrollDisabled',
    'CameraHubPrompterAutoScrollEnabled',
    'CameraHubPrompterBackgroundColorChanged',
    'CameraHubPrompterBrightnessChanged',
    'CameraHubPrompterChannelsChanged',
    'CameraHubPrompterConnected',
    'CameraHubPrompterDisconnected',
    'CameraHubPrompterFontChanged',
    'CameraHubPrompterFontColorChanged',
    'CameraHubPrompterFontSizeChanged',
    'CameraHubPrompterHorizontalMarginChanged',
    'CameraHubPrompterLineSpacingChanged',
    'CameraHubPrompterModeChanged',
    'CameraHubPrompterOpacityChanged',
    'CameraHubPrompterScrollSpeedChanged',
    'CameraHubPrompterSelectedChannelChanged',
    'CameraHubPrompterSelectedChapterChanged',
    'CameraHubPrompterVerticalMarginChanged',
    'WaveLinkConnected',
    'WaveLinkDisconnected',
    'WaveLinkFilterAdded',
    'WaveLinkFilterBypassStateChanged',
    'WaveLinkFilterChanged',
    'WaveLinkFilterDeleted',
    'WaveLinkInputLevelMeterChanged',
    'WaveLinkInputMuteChanged',
    'WaveLinkInputNameChanged',
    'WaveLinkInputVolumeChanged',
    'WaveLinkMicrophoneBalanceChanged',
    'WaveLinkMicrophoneGainChanged',
    'WaveLinkMicrophoneMuteChanged',
    'WaveLinkMicrophoneOutputVolumeChanged',
    'WaveLinkMicrophoneSettingChanged',
    'WaveLinkOutputLevelMeterChanged',
    'WaveLinkOutputMuteChanged',
    'WaveLinkOutputSwitched',
    'WaveLinkOutputVolumeChanged',
    'WaveLinkSelectedOutputChanged',
  ],
  StreamlabsDesktop: [
    'Connected',
    'Disconnected',
    'RecordingStarted',
    'RecordingStopped',
    'SceneChanged',
    'StreamingStarted',
    'StreamingStopped',
  ],
  SpeakerBot: ['Connected', 'Disconnected'],
  Fourthwall: [
    'Donation',
    'GiftPurchase',
    'OrderPlaced',
    'OrderUpdated',
    'ProductCreated',
    'ProductUpdated',
    'SubscriptionChanged',
    'SubscriptionExpired',
    'SubscriptionPurchased',
  ],
  Trovo: [
    'BroadcasterAuthenticated',
    'BroadcasterChatConnected',
    'BroadcasterChatDisconnected',
    'ChatMessage',
    'CustomSpellCast',
    'FirstWords',
    'Follow',
    'GiftSubscription',
    'MassGiftSubscription',
    'PresentViewers',
    'Raid',
    'Resubscription',
    'SpellCast',
    'StreamOffline',
    'StreamOnline',
    'Subscription',
  ],
  VStream: [
    'BroadcasterAuthenticated',
    'BroadcasterChatConnected',
    'BroadcasterChatDisconnected',
    'ChatMessage',
    'FirstWords',
    'NewFollower',
    'PresentViewers',
    'StreamOffline',
    'StreamOnline',
  ],
  ThrowingSystem: [
    'Connected',
    'EventsConnected',
    'EventsDisconnected',
    'ItemHit',
    'TriggerActivated',
    'TriggerEnded',
    'WebsocketConnected',
    'WebsocketDisconnected',
  ],
} as const;
